import './globals.css'
import Header from './components/Header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* HEADER  */}
        <Header/>

        <div className="flex min-h-screen flex-col items-center justify-between p-12"> 

        {children}
        </div>
      </body>
    </html>
  )
}
